# Import Libraries

In [1]:
import numpy as np #Build DT Model from scratch
import pandas as pd
from sklearn.preprocessing import OneHotEncoder #Preprocess text data
import os

#The following libraries are used to test for hyperparameters for the DT model made with numpy 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/airbnb/airbnbData_Prepared.csv

# Data Preprocessing

In [2]:
airbnb = pd.read_csv('/kaggle/input/airbnb/airbnbData_Prepared.csv')

In [3]:
airbnb.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_group_cleansed,room_type,accommodates,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,n_host_verifications
0,0.800000,0.170000,False,8,8,True,True,Manhattan,Entire home/apt,1,...,4.79,4.86,4.41,False,3,3,0,0,0.33,9
1,0.090000,0.690000,False,1,1,True,True,Brooklyn,Entire home/apt,3,...,4.80,4.71,4.64,False,1,1,0,0,4.86,6
2,1.000000,0.250000,False,1,1,True,True,Brooklyn,Entire home/apt,4,...,5.00,4.50,5.00,False,1,1,0,0,0.02,3
3,1.000000,1.000000,False,1,1,True,False,Manhattan,Private room,2,...,4.42,4.87,4.36,False,1,0,1,0,3.68,4
4,0.890731,0.768297,False,1,1,True,True,Manhattan,Private room,1,...,4.95,4.94,4.92,False,1,0,1,0,0.87,7

In [4]:
airbnb.shape

(28022, 43)

In [5]:
airbnb.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_group_cleansed,room_type,accommodates,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,n_host_verifications
0,0.800000,0.170000,False,8,8,True,True,Manhattan,Entire home/apt,1,...,4.79,4.86,4.41,False,3,3,0,0,0.33,9
1,0.090000,0.690000,False,1,1,True,True,Brooklyn,Entire home/apt,3,...,4.80,4.71,4.64,False,1,1,0,0,4.86,6
2,1.000000,0.250000,False,1,1,True,True,Brooklyn,Entire home/apt,4,...,5.00,4.50,5.00,False,1,1,0,0,0.02,3
3,1.000000,1.000000,False,1,1,True,False,Manhattan,Private room,2,...,4.42,4.87,4.36,False,1,0,1,0,3.68,4
4,0.890731,0.768297,False,1,1,True,True,Manhattan,Private room,1,...,4.95,4.94,4.92,False,1,0,1,0,0.87,7

In [6]:
list(airbnb.loc[:, airbnb.columns != 'host_is_superhost'])

['host_response_rate',
 'host_acceptance_rate',
 'host_listings_count',
 'host_total_listings_count',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood_group_cleansed',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'review_scores_rating',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'n_host_verifications']

### One Hot Encoding

In [7]:
encode_list = airbnb.select_dtypes(object)

In [8]:
encode_list

      neighbourhood_group_cleansed        room_type
0                        Manhattan  Entire home/apt
1                         Brooklyn  Entire home/apt
2                         Brooklyn  Entire home/apt
3                        Manhattan     Private room
4                        Manhattan     Private room
...                            ...              ...
28017                       Queens     Private room
28018                     Brooklyn  Entire home/apt
28019                     Brooklyn     Private room
28020                     Brooklyn  Entire home/apt
28021                       Queens     Private room

[28022 rows x 2 columns]

In [9]:
encoder = OneHotEncoder(sparse_output=False)

In [10]:
results = encoder.fit_transform(encode_list)

In [11]:
airbnb_encoded = pd.DataFrame(results)

In [12]:
airbnb_encoded.head()

     0    1    2    3    4    5    6    7    8
0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0

In [13]:
airbnb_encoded.columns = encoder.get_feature_names_out(['neighbourhood_group_cleansed','room_type'])

In [14]:
airbnb_encoded.head()

,neighbourhood_group_cleansed_Bronx,neighbourhood_group_cleansed_Brooklyn,neighbourhood_group_cleansed_Manhattan,neighbourhood_group_cleansed_Queens,neighbourhood_group_cleansed_Staten Island,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
airbnb.drop(columns=['neighbourhood_group_cleansed','room_type'], inplace=True)

In [16]:
airbnb.shape

(28022, 41)

In [17]:
airbnb = pd.concat([airbnb, airbnb_encoded], axis=1)

In [18]:
airbnb.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,accommodates,bathrooms,bedrooms,...,n_host_verifications,neighbourhood_group_cleansed_Bronx,neighbourhood_group_cleansed_Brooklyn,neighbourhood_group_cleansed_Manhattan,neighbourhood_group_cleansed_Queens,neighbourhood_group_cleansed_Staten Island,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,0.800000,0.170000,False,8,8,True,True,1,1.0,1.323567,...,9,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.090000,0.690000,False,1,1,True,True,3,1.0,1.000000,...,6,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.000000,0.250000,False,1,1,True,True,4,1.5,2.000000,...,3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,1.000000,1.000000,False,1,1,True,False,2,1.0,1.000000,...,4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.890731,0.768297,False,1,1,True,True,1,1.0,1.000000,...,7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
label = airbnb.pop('host_is_superhost')
airbnb['host_is_superhost'] = label

In [20]:
airbnb.head()

,host_response_rate,host_acceptance_rate,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,accommodates,bathrooms,bedrooms,beds,...,neighbourhood_group_cleansed_Bronx,neighbourhood_group_cleansed_Brooklyn,neighbourhood_group_cleansed_Manhattan,neighbourhood_group_cleansed_Queens,neighbourhood_group_cleansed_Staten Island,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room,host_is_superhost
0,0.800000,0.170000,8,8,True,True,1,1.0,1.323567,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,False
1,0.090000,0.690000,1,1,True,True,3,1.0,1.000000,3.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,False
2,1.000000,0.250000,1,1,True,True,4,1.5,2.000000,2.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,False
3,1.000000,1.000000,1,1,True,False,2,1.0,1.000000,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,False
4,0.890731,0.768297,1,1,True,True,1,1.0,1.000000,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,False

# Find best Hyperparameters

In [21]:
X = airbnb.drop(columns='host_is_superhost')
y = airbnb['host_is_superhost']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=123)

In [22]:
def train_test_DT(X_train, X_test, y_train, y_test, depth, leaf=1, crit='entropy'):
    model = DecisionTreeClassifier(max_depth=depth, min_samples_leaf=leaf, criterion=crit)
    model.fit(X_train, y_train)
    label_predictions = model.predict(X_test)
    acc_score = accuracy_score(y_test, label_predictions)
    
    return acc_score

In [23]:
hyp = [1, 2, 4, 8, 16, 32]

acc = []

for i in hyp:
    score = train_test_DT(X_train, X_test, y_train, y_test, i, 1)
    print('max depth: ' + str(i) + ' accuracy score: ' + str(score))
    acc.append(float(score))

max depth: 1 accuracy score: 0.7563797577854672
max depth: 2 accuracy score: 0.7563797577854672
max depth: 4 accuracy score: 0.810878027681661
max depth: 8 accuracy score: 0.833044982698962
max depth: 16 accuracy score: 0.8135813148788927
max depth: 32 accuracy score: 0.8027681660899654

# *Decision Tree From Scratch (with numpy)*

# Node Class

In [24]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):

#decision node information
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.info_grain = info_gain
        
        #leaf node value
        self.value = value

# DecisionTreeClassifier Class

In [25]:
import numpy as np

class DecisionTreeClassifier:
    def __init__(self, min_samples_leaf=8, max_depth=10):
        self.root = None
        self.min_samples_leaf = min_samples_leaf
        self.max_depth = max_depth

    def build_tree(self, dataset, curr_depth=0):
        X = dataset[:, :-1]
        y = dataset[:, -1]

        num_samples, num_features = np.shape(X)

        if num_samples >= self.min_samples_leaf and curr_depth < self.max_depth:
            best_split = self.get_best_split(dataset, num_samples, num_features)

            if best_split.get("info_gain", 0) > 0:
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth + 1)
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth + 1)
                return Node(
                    best_split["feature_index"],
                    best_split["threshold"],
                    left_subtree,
                    right_subtree,
                    best_split["info_gain"],
                )

        leaf_value = self.calculate_leaf_value(y)
        return Node(value=leaf_value)

    def get_best_split(self, dataset, num_samples, num_features):
        best_split = {}
        max_info_gain = -float("inf")

        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)

            for threshold in possible_thresholds:
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                if len(dataset_left) > 0 and len(dataset_right) > 0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    if curr_info_gain > max_info_gain:
                        best_split = {
                            "feature_index": feature_index,
                            "threshold": threshold,
                            "dataset_left": dataset_left,
                            "dataset_right": dataset_right,
                            "info_gain": curr_info_gain,
                        }
                        max_info_gain = curr_info_gain

        return best_split

    def split(self, dataset, feature_index, threshold):
        dataset_left = np.array([row for row in dataset if row[feature_index] <= threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index] > threshold])
        return dataset_left, dataset_right

    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)

        if mode == "gini":
            gain = self.gini_index(parent) - (
                weight_l * self.gini_index(l_child) + weight_r * self.gini_index(r_child)
            )
        else:
            gain = self.entropy(parent) - (
                weight_l * self.entropy(l_child) + weight_r * self.entropy(r_child)
            )
        return gain

    def entropy(self, y):
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy

    def gini_index(self, y):
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini

    def calculate_leaf_value(self, Y):
        Y = list(Y)
        return max(Y, key=Y.count)

    def print_tree(self, tree=None, indent=" "):
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)
        else:
            print("X_" + str(tree.feature_index), "<=", tree.threshold, "?", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)

    def fit(self, X, Y):
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)

    def predict(self, X):
        predictions = [self.make_prediction(x, self.root) for x in X]
        return predictions

    def make_prediction(self, x, tree):
        if tree.value is not None:
            return tree.value

        feature_val = x[tree.feature_index]
        if feature_val <= tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

# Train and Test Model

In [26]:
X_train_np = X_train.to_numpy() 
X_test_np = X_test.to_numpy()

y_train_np = y_train.to_numpy().reshape(-1,1)
y_test_np = y_test.to_numpy().reshape(-1,1)

In [27]:
dt_final = DecisionTreeClassifier(min_samples_leaf=4, max_depth=8)
dt_final.fit(X_train_np, y_train_np)

y_pred = dt_final.predict(X_test_np)

accuracy = accuracy_score(y_pred, y_test_np)
accuracy

0.829909169550173